name: Tests

on:
  push:
  pull_request:

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build '.#patched-simd-json-src'
      - run: nix build -L '.#unit-test'
  integration-test:
    name: Integration Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build '.#patched-simd-json-src'
      - run: nix run '.#integration-test'
